<?php

declare(strict_types=1);

return [
    'name' => 'NatalCode',
    'legalName' => 'NatalCode Agência Digital',
    'tagline' => 'Estratégia, design e tecnologia para negócios digitais.',
    'brand' => [
        'homeHref' => '/',
        'logoSrc' => '/assets/img/brand/natalcode_logo_horizontal_black_1158x314.png',
        'logoLightSrc' => '/assets/img/brand/natalcode_logo_horizontal_black_1158x314.png',
        'logoDarkSrc' => '/assets/img/brand/natalcode_logo_horizontal_white_1158x314.png',
        'logoAlt' => 'NatalCode',
        'motto' => 'Código com proposito, design com resultado.',
    ],
    'contact' => [
        'email' => 'contato@natalcode.com.br',
        'address' => 'Atendimento remoto para todo o Brasil.',
        'mapUrl' => 'https://natalcode.com.br/contato',
    ],
    'social' => [
        'instagram' => [
            'url' => 'https://www.instagram.com/natalcode/',
            'label' => 'Instagram oficial: @natalcode',
        ],
    ],
    'institutional' => [
        'statuteExcerpt' => 'A NatalCode é uma agência digital focada em estratégia, design e desenvolvimento web, com atuação orientada a resultado e experiência do usuário.',
        'contactSummary' => 'Atendemos empresas, profissionais e projetos que precisam de presença digital clara, rápida e confiável.',
        'footerSummary' => 'Agência digital • Desenvolvimento web • SEO • Performance',
    ],
    'footer' => [
        'kicker' => 'Presença digital orientada a resultado',
        'description' => 'Da landing page ao sistema sob medida, estruturamos projetos digitais com visão de produto, performance e evolução continua.',
        'navGroups' => [
            [
                'title' => 'Institucional',
                'links' => [
                    ['path' => '/', 'key' => 'inicio'],
                    ['path' => '/quem-somos', 'key' => 'quem-somos'],
                    ['path' => '/quem-somos/historia', 'key' => 'historia'],
                    ['path' => '/quem-somos/fundador', 'key' => 'fundador'],
                    ['path' => '/quem-somos/nossa-marca', 'key' => 'nossa-marca'],
                    ['path' => '/quem-somos/estatuto', 'key' => 'estatuto'],
                    ['path' => '/quem-somos/gestao-cede', 'key' => 'gestao-cede'],
                    ['path' => '/quem-somos/base-de-conhecimento', 'key' => 'biblioteca'],
                    ['path' => '/contato', 'key' => 'contato'],
                    ['path' => '/politica-de-privacidade', 'key' => 'politica-de-privacidade'],
                    ['path' => '/termos-de-uso', 'key' => 'termos-de-uso'],
                ],
            ],
            [
                'title' => 'Recursos',
                'links' => [
                    ['path' => '/portfolio', 'key' => 'portfolio'],
                    ['path' => '/loja', 'key' => 'loja'],
                    ['path' => '/loja/livraria', 'key' => 'livraria'],
                    ['path' => '/loja/bazar', 'key' => 'bazar'],
                ],
            ],
        ],
        'contactKicker' => 'Vamos conversar',
        'contactTitle' => 'Fale com a NatalCode',
        'contactLead' => 'Envie sua ideia e retornamos com próximo passo, escopo inicial e estimativa.',
        'bottomNote' => 'Atendimento nacional',
        'cnpj' => '04.242.556/0001-45',
    ],
    'portfolio' => [
        'kicker' => 'Portfolio NatalCode',
        'title' => 'Catalogo de landing pages e sites web',
        'lead' => 'Galeria de modelos por segmento: landing pages e sites para nichos especificos.',
        'note' => 'As imagens abaixo sao demonstrativas. Podemos substituir por screenshots reais de cada projeto publicado.',
        'items' => [
            [
                'title' => 'Modelo de Landing Page',
                'category' => 'Landing Page',
                'segment' => 'Landing Pages',
                'summary' => 'Estrutura focada em conversao com oferta, prova social e CTA principal.',
                'url' => 'https://natalcode.com.br/',
                'urlLabel' => 'Ver demo',
                'image' => '/assets/img/portifolio/cedern.png',
                'alt' => 'Preview de home de landing page',
            ],
            [
                'title' => 'Modelo de Site para Supermercado',
                'category' => 'Site Web',
                'segment' => 'Supermercados',
                'summary' => 'Home com foco em ofertas, categorias e destaque de campanhas sazonais.',
                'url' => 'https://natalcode.com.br/estudos',
                'urlLabel' => 'Ver demo',
                'image' => '/assets/img/portifolio/cedern.png',
                'alt' => 'Preview de home para supermercado',
            ],
            [
                'title' => 'Modelo de Site para Padaria',
                'category' => 'Site Web',
                'segment' => 'Padarias',
                'summary' => 'Pagina com cardapio em destaque, encomendas e chamada para WhatsApp.',
                'url' => 'https://natalcode.com.br/quem-somos',
                'urlLabel' => 'Ver demo',
                'image' => '/assets/img/portifolio/cedern.png',
                'alt' => 'Preview de home para padaria',
            ],
            [
                'title' => 'Modelo de Site para Dentista',
                'category' => 'Site Web',
                'segment' => 'Dentistas',
                'summary' => 'Home com especialidades, credenciais, depoimentos e conversao por agendamento.',
                'url' => 'https://natalcode.com.br/contato',
                'urlLabel' => 'Ver demo',
                'image' => '/assets/img/portifolio/cedern.png',
                'alt' => 'Preview de home para clinica odontologica',
            ],
            [
                'title' => 'Modelo de Site para Medico',
                'category' => 'Aplicacao Web',
                'segment' => 'Medicos',
                'summary' => 'Estrutura profissional com servicos, biografia, localizacao e CTA de consulta.',
                'url' => 'https://natalcode.com.br/entrar',
                'urlLabel' => 'Ver demo',
                'image' => '/assets/img/portifolio/cedern.png',
                'alt' => 'Preview de home para medico',
            ],
            [
                'title' => 'Modelo de Site para Psicologo',
                'category' => 'Pagina Comercial',
                'segment' => 'Psicologos',
                'summary' => 'Layout humanizado para autoridade, explicacao da abordagem e agendamento.',
                'url' => 'https://natalcode.com.br/agenda',
                'urlLabel' => 'Ver demo',
                'image' => '/assets/img/portifolio/cedern.png',
                'alt' => 'Preview de home para psicologo',
            ],
        ],
    ],
];
